document.writeln("<header class=\'mdc-top-app-bar\'>");
document.writeln("    <div class=\'mdc-top-app-bar__row\'>");
document.writeln("        <section class=\'mdc-top-app-bar__section mdc-top-app-bar__section--align-start\'>");
document.writeln("            <span class=\'mdc-top-app-bar__title\'>Merak的博客</span>");
document.writeln("        </section>");
document.writeln("        <section class=\'mdc-top-app-bar__section mdc-top-app-bar__section--align-end\' role=\'toolbar\'>");
document.writeln("            <a class=\'material-icons mdc-top-app-bar__action-item mdc-icon-button\' aria-label=\'Home\'");
document.writeln("                href=\'./index.html\'>home</a>");
document.writeln("            <a class=\'material-icons mdc-top-app-bar__action-item mdc-icon-button\' aria-label=\'Article\'");
document.writeln("                href=\'./index.html#card\'>article</a>");
document.writeln("            <a class=\'material-icons mdc-top-app-bar__action-item mdc-icon-button\' aria-label=\'account_circle\'");
document.writeln("                href=\'./about.html\'>account_circle</a>");
document.writeln("        </section>");
document.writeln("    </div>");
document.writeln("</header>");
document.writeln("<main class=\'mdc-top-app-bar--fixed-adjust\'>");